[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mlproject"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = [
  "pandas",
  "scikit-learn",
  "numpy",
  "seaborn"
]

[tool.setuptools.packages.find]
where = ["src"]